# Example Lovelace Dashboard Configuration for Baby Monitor

This file contains example dashboard configurations for the Baby Monitor integration.

## Complete Baby Dashboard

```yaml
title: Baby Monitor Dashboard
views:
  - title: Overview
    path: overview
    cards:
      - type: markdown
        content: |
          # 👶 Anika's Care Dashboard
          Welcome to Anika's monitoring dashboard. Use the quick actions below for fast logging.
        
      - type: entities
        title: 🏃 Quick Actions
        show_header_toggle: false
        entities:
          - button.anika_quick_wet_diaper
          - button.anika_quick_dirty_diaper
          - button.anika_quick_wet_dirty_diaper
          - button.anika_quick_bottle_feeding
          - button.anika_quick_breast_feeding_left
          - button.anika_quick_breast_feeding_right
          - button.anika_quick_breast_feeding_both
          - button.anika_start_sleep
          - button.anika_end_sleep

      - type: entities
        title: 📊 Current Status
        show_header_toggle: false
        entities:
          - entity: sensor.anika_last_diaper_change
            secondary_info: last-changed
          - entity: sensor.anika_last_feeding
            secondary_info: last-changed
          - entity: sensor.anika_last_sleep
            secondary_info: last-changed
          - entity: sensor.anika_temperature
            secondary_info: last-changed

      - type: entities
        title: 📈 Today's Summary
        show_header_toggle: false
        entities:
          - type: attribute
            entity: sensor.anika_daily_summary
            attribute: diaper_changes
            name: Diaper Changes Today
            icon: mdi:baby
          - type: attribute
            entity: sensor.anika_daily_summary
            attribute: wet_diapers
            name: Wet Diapers
            icon: mdi:water
          - type: attribute
            entity: sensor.anika_daily_summary
            attribute: dirty_diapers
            name: Dirty Diapers
            icon: mdi:delete-variant
          - type: attribute
            entity: sensor.anika_daily_summary
            attribute: feedings
            name: Feedings Today
            icon: mdi:bottle-tonic-skull
          - type: attribute
            entity: sensor.anika_daily_summary
            attribute: total_feeding_amount_ml
            name: Total Fed (ml)
            icon: mdi:cup-water
          - type: attribute
            entity: sensor.anika_daily_summary
            attribute: sleep_sessions
            name: Sleep Sessions
            icon: mdi:sleep
          - type: attribute
            entity: sensor.anika_daily_summary
            attribute: total_sleep_formatted
            name: Total Sleep
            icon: mdi:sleep

  - title: Goals & Status
    path: goals
    cards:
      - type: markdown
        content: |
          # 🎯 Daily Goals Tracking
          Monitor progress toward daily care goals
        
      - type: entities
        title: Progress Toward Daily Goals
        show_header_toggle: false
        entities:
          - type: attribute
            entity: sensor.anika_total_diaper_changes
            attribute: diaper_status
            name: Diaper Changes Status
            icon: mdi:baby-carriage
          - type: attribute
            entity: sensor.anika_total_diaper_changes
            attribute: progress_percentage
            name: Diaper Changes Progress
            icon: mdi:progress-check
            suffix: "%"
          - type: divider
          - type: attribute
            entity: sensor.anika_total_diaper_changes
            attribute: wet_diaper_status
            name: Wet Diapers Status
            icon: mdi:water
          - type: attribute
            entity: sensor.anika_total_diaper_changes
            attribute: wet_today
            name: Wet Diapers Today
            icon: mdi:water
          - type: attribute
            entity: sensor.anika_total_diaper_changes
            attribute: min_wet_diapers_goal
            name: Wet Diapers Goal
            icon: mdi:target
          - type: divider
          - type: attribute
            entity: sensor.anika_total_feedings
            attribute: feeding_status
            name: Feeding Status
            icon: mdi:bottle-tonic-skull
          - type: attribute
            entity: sensor.anika_total_feedings
            attribute: progress_percentage
            name: Feeding Progress
            icon: mdi:progress-check
            suffix: "%"
          - type: divider
          - type: attribute
            entity: sensor.anika_tummy_time_today
            attribute: tummy_time_status
            name: Tummy Time Status
            icon: mdi:baby
          - type: attribute
            entity: sensor.anika_tummy_time_today
            attribute: progress_percentage
            name: Tummy Time Progress
            icon: mdi:progress-check
            suffix: "%"

      - type: markdown
        title: Goals Summary
        content: |
          ### Today's Progress
          
          **Diaper Changes:** {{ state_attr('sensor.anika_total_diaper_changes', 'today_count') }} / {{ state_attr('sensor.anika_total_diaper_changes', 'min_diapers_goal') }}
          - Status: **{{ state_attr('sensor.anika_total_diaper_changes', 'diaper_status') }}**
          - Progress: {{ state_attr('sensor.anika_total_diaper_changes', 'progress_percentage') }}%
          
          **Wet Diapers:** {{ state_attr('sensor.anika_total_diaper_changes', 'wet_today') }} / {{ state_attr('sensor.anika_total_diaper_changes', 'min_wet_diapers_goal') }}
          - Status: **{{ state_attr('sensor.anika_total_diaper_changes', 'wet_diaper_status') }}**
          
          **Feedings:** {{ state_attr('sensor.anika_total_feedings', 'today_count') }} / {{ state_attr('sensor.anika_total_feedings', 'min_feedings_goal') }}
          - Status: **{{ state_attr('sensor.anika_total_feedings', 'feeding_status') }}**
          - Progress: {{ state_attr('sensor.anika_total_feedings', 'progress_percentage') }}%
          
          **Tummy Time:** {{ states('sensor.anika_tummy_time_today') }} / {{ state_attr('sensor.anika_tummy_time_today', 'target_daily_minutes') }} min
          - Status: **{{ state_attr('sensor.anika_tummy_time_today', 'tummy_time_status') }}**
          - Progress: {{ state_attr('sensor.anika_tummy_time_today', 'progress_percentage') }}%
          
          ---
          
          💡 **Tip:** You can adjust these goals in Settings → Devices & Services → Baby Monitor → Configure

      - type: gauge
        name: Daily Diaper Progress
        entity: sensor.anika_total_diaper_changes
        attribute: progress_percentage
        min: 0
        max: 100
        severity:
          green: 100
          yellow: 60
          red: 0

      - type: gauge
        name: Daily Feeding Progress
        entity: sensor.anika_total_feedings
        attribute: progress_percentage
        min: 0
        max: 100
        severity:
          green: 100
          yellow: 60
          red: 0

  - title: Statistics
    path: stats
    cards:
      - type: statistics-graph
        title: Feeding Amounts (Last 7 Days)
        entities:
          - sensor.anika_average_feeding_amount
        period: day
        days_to_show: 7
        stat_types:
          - mean
          - max
          - min

      - type: statistics-graph
        title: Sleep Duration (Last 7 Days)
        entities:
          - sensor.anika_average_sleep_duration
        period: day
        days_to_show: 7
        stat_types:
          - mean

      - type: entities
        title: 📊 All Time Statistics
        show_header_toggle: false
        entities:
          - sensor.anika_total_diaper_changes
          - sensor.anika_total_feedings
          - sensor.anika_total_sleep_sessions
          - sensor.anika_average_feeding_amount
          - sensor.anika_average_sleep_duration

      - type: entities
        title: 🗓️ Weekly Summary
        show_header_toggle: false
        entities:
          - type: attribute
            entity: sensor.anika_weekly_summary
            attribute: total_diaper_changes
            name: Total Diaper Changes (7d)
          - type: attribute
            entity: sensor.anika_weekly_summary
            attribute: total_feedings
            name: Total Feedings (7d)
          - type: attribute
            entity: sensor.anika_weekly_summary
            attribute: avg_diapers_per_day
            name: Avg Diapers/Day
          - type: attribute
            entity: sensor.anika_weekly_summary
            attribute: avg_feedings_per_day
            name: Avg Feedings/Day
          - type: attribute
            entity: sensor.anika_weekly_summary
            attribute: avg_sleep_per_day_formatted
            name: Avg Sleep/Day

  - title: Health & Growth
    path: health
    cards:
      - type: entities
        title: 🌡️ Health Monitoring
        show_header_toggle: false
        entities:
          - sensor.anika_temperature

      - type: markdown
        content: |
          ## 📏 Growth Tracking
          Use the services to log weight and height measurements during doctor visits.
          
          **Recent Services:**
          - `babymonitor.log_weight`
          - `babymonitor.log_height`
          - `babymonitor.log_medication`
          - `babymonitor.log_milestone`

      - type: button
        name: Log Temperature
        tap_action:
          action: call-service
          service: babymonitor.log_temperature
          data:
            baby_name: Anika
          target: {}

  - title: Manual Logging
    path: manual
    cards:
      - type: markdown
        content: |
          ## 📝 Manual Activity Logging
          Use these service calls for detailed logging with custom notes and amounts.

      - type: button
        name: Log Diaper Change
        tap_action:
          action: call-service
          service: babymonitor.log_diaper_change
          data:
            baby_name: Anika
            diaper_type: wet
            notes: "Manual log"
          target: {}

      - type: button
        name: Log Feeding
        tap_action:
          action: call-service
          service: babymonitor.log_feeding
          data:
            baby_name: Anika
            feeding_type: bottle
            feeding_amount: 150
            feeding_duration: 20
            notes: "Custom feeding"
          target: {}

      - type: button
        name: Log Milestone
        tap_action:
          action: call-service
          service: babymonitor.log_milestone
          data:
            baby_name: Anika
            milestone_name: "First laugh"
            notes: "Such a beautiful sound!"
          target: {}
```

## Compact Mobile Dashboard

```yaml
title: Anika - Mobile
views:
  - title: Quick
    path: mobile-quick
    panel: true
    cards:
      - type: grid
        columns: 2
        cards:
          - type: button
            entity: button.anika_quick_wet_diaper
            name: Wet
            icon: mdi:water
            tap_action:
              action: toggle

          - type: button
            entity: button.anika_quick_dirty_diaper
            name: Dirty
            icon: mdi:delete-variant
            tap_action:
              action: toggle

          - type: button
            entity: button.anika_quick_bottle_feeding
            name: Bottle
            icon: mdi:bottle-tonic-skull
            tap_action:
              action: toggle

          - type: button
            entity: button.anika_quick_breast_feeding_both
            name: Breast
            icon: mdi:human-female
            tap_action:
              action: toggle

          - type: button
            entity: button.anika_start_sleep
            name: Sleep Start
            icon: mdi:sleep
            tap_action:
              action: toggle

          - type: button
            entity: button.anika_end_sleep
            name: Sleep End
            icon: mdi:sleep-off
            tap_action:
              action: toggle

      - type: entities
        title: Status
        entities:
          - sensor.anika_last_diaper_change
          - sensor.anika_last_feeding
          - sensor.anika_last_sleep
          - sensor.anika_daily_summary
```

## Picture Elements Dashboard (with baby photo)

```yaml
title: Anika's Room
views:
  - title: Visual
    path: visual
    panel: true
    cards:
      - type: picture-elements
        image: /local/baby_room.jpg  # Add your baby's photo here
        elements:
          # Quick action buttons overlaid on image
          - type: state-icon
            entity: button.anika_quick_wet_diaper
            style:
              top: 20%
              left: 20%
              --paper-item-icon-color: blue
            tap_action:
              action: toggle

          - type: state-icon
            entity: button.anika_quick_dirty_diaper
            style:
              top: 20%
              left: 40%
              --paper-item-icon-color: brown
            tap_action:
              action: toggle

          - type: state-icon
            entity: button.anika_quick_bottle_feeding
            style:
              top: 40%
              left: 20%
              --paper-item-icon-color: green
            tap_action:
              action: toggle

          - type: state-icon
            entity: button.anika_start_sleep
            style:
              top: 40%
              left: 40%
              --paper-item-icon-color: purple
            tap_action:
              action: toggle

          # Status display
          - type: state-label
            entity: sensor.anika_last_feeding
            attribute: time_ago
            prefix: "Last fed: "
            style:
              top: 80%
              left: 50%
              color: white
              font-size: 16px
              background-color: rgba(0, 0, 0, 0.3)
              padding: 4px 8px
              border-radius: 4px

          - type: state-label
            entity: sensor.anika_last_diaper_change
            attribute: time_ago
            prefix: "Last changed: "
            style:
              top: 85%
              left: 50%
              color: white
              font-size: 16px
              background-color: rgba(0, 0, 0, 0.3)
              padding: 4px 8px
              border-radius: 4px
```

## Chart Dashboard

```yaml
title: Anika - Analytics
views:
  - title: Charts
    path: charts
    cards:
      - type: history-graph
        title: Activity Timeline (24h)
        hours_to_show: 24
        entities:
          - sensor.anika_last_diaper_change
          - sensor.anika_last_feeding
          - sensor.anika_last_sleep

      - type: statistics-graph
        title: Daily Feeding Amounts
        entities:
          - sensor.anika_average_feeding_amount
        period: day
        days_to_show: 14

      - type: statistics-graph
        title: Sleep Patterns
        entities:
          - sensor.anika_average_sleep_duration
        period: day
        days_to_show: 14

      - type: custom:mini-graph-card
        name: Temperature Trend
        entities:
          - entity: sensor.anika_temperature
        hours_to_show: 168  # 1 week
        points_per_hour: 0.25
        line_color: orange
        line_width: 2
        animate: true
```

## Diaper Tracking Dashboard

```yaml
title: Diaper Tracking
views:
  - title: Diaper Stats
    path: diaper-stats
    cards:
      # Simple card showing today's diaper counts by type
      - type: entities
        title: 🍼 Today's Diaper Changes
        show_header_toggle: false
        entities:
          - type: attribute
            entity: sensor.anika_total_diaper_changes
            attribute: today_count
            name: Total Changes Today
            icon: mdi:baby-carriage
          - type: attribute
            entity: sensor.anika_total_diaper_changes
            attribute: wet_today
            name: Wet Diapers
            icon: mdi:water
          - type: attribute
            entity: sensor.anika_total_diaper_changes
            attribute: dirty_today
            name: Dirty Diapers
            icon: mdi:delete-variant
          - type: divider
          - entity: sensor.anika_diaper_change_frequency
            name: Average Per Day (7d)
            icon: mdi:chart-line

      # Visual glance card for quick overview
      - type: glance
        title: Diaper Summary
        show_name: true
        show_state: true
        columns: 3
        entities:
          - entity: sensor.anika_total_diaper_changes
            name: Today Total
            icon: mdi:baby-carriage
            attribute: today_count
          - entity: sensor.anika_total_diaper_changes
            name: Wet
            icon: mdi:water
            attribute: wet_today
          - entity: sensor.anika_total_diaper_changes
            name: Dirty
            icon: mdi:delete-variant
            attribute: dirty_today

      # Detailed breakdown with weekly comparison
      - type: markdown
        title: Diaper Change Details
        content: |
          ### Today's Diaper Changes
          
          **Total:** {{ state_attr('sensor.anika_total_diaper_changes', 'today_count') }} changes
          
          - 💧 **Wet diapers:** {{ state_attr('sensor.anika_total_diaper_changes', 'wet_today') }}
          - 💩 **Dirty diapers:** {{ state_attr('sensor.anika_total_diaper_changes', 'dirty_today') }}
          
          ---
          
          ### Weekly Average
          
          **Frequency:** {{ states('sensor.anika_diaper_change_frequency') }} changes per day
          
          **This Week:**
          - Total changes: {{ state_attr('sensor.anika_diaper_change_frequency', 'changes_this_week') }}
          - Wet changes: {{ state_attr('sensor.anika_diaper_change_frequency', 'wet_changes_week') }}
          - Dirty changes: {{ state_attr('sensor.anika_diaper_change_frequency', 'dirty_changes_week') }}
          
          Status: **{{ state_attr('sensor.anika_diaper_change_frequency', 'frequency_status') }}**
          
          *Normal range: {{ state_attr('sensor.anika_diaper_change_frequency', 'normal_range') }}*

      # Recent diaper changes history
      - type: entities
        title: 📋 Recent Activity
        show_header_toggle: false
        entities:
          - entity: sensor.anika_last_diaper_change
            type: attribute
            attribute: time_ago
            name: Last Change
            icon: mdi:clock-outline
          - entity: sensor.anika_last_diaper_change
            type: attribute
            attribute: diaper_type
            name: Type
            icon: mdi:information-outline
```

## Usage Instructions

1. Copy the desired dashboard configuration
2. Go to your Home Assistant Lovelace dashboard
3. Click the three dots menu → "Edit Dashboard"
4. Click "Raw configuration editor"
5. Paste the configuration
6. Replace "Anika" with your baby's name if different
7. Save the configuration

## Customization Tips

- **Icons**: Change the `mdi:` icons to match your preferences
- **Colors**: Use the `--paper-item-icon-color` property to customize button colors
- **Layout**: Adjust the `columns` property in grid cards for different layouts
- **Automation**: Add more service call buttons for different scenarios
- **Photos**: Add baby photos using the picture-elements card type
- **Themes**: The dashboard works with any Home Assistant theme

## Mobile App Widget Ideas

Create mobile app widgets using the quick action buttons:
- Long press the Home Assistant app icon
- Add widget
- Select "Button" widget type  
- Choose your quick action buttons
- Place on home screen for instant access